# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros

In [3]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [4]:
arr=np.array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
arr1=np.array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [7]:
arr2=np.arange(10,51)

#### Create an array of all the even integers from 10 to 50

In [ ]:
arr3=np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
arr4=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr4)

#### Create a 3x3 identity matrix

In [9]:
arr5=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(arr5)

#### Use NumPy to generate a random number between 0 and 1

In [13]:
import random
arr = np.array([np.random.rand()])
print(arr)

[0.68961003]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [14]:
arr = np.random.normal(0, 1, 25)
print(arr)

[-0.65364925  0.64170526  1.881833   -0.24287296 -0.96912522  1.83473046
 -1.43683453  0.01239894 -1.3607724  -1.44367753  0.27178491 -0.55081412
  0.6876117   0.49917446  0.29867608  0.54231028 -0.88137287 -0.97496519
  1.27233136  0.6490137   0.13251304 -1.57897341  0.35550117 -0.08040983
 -0.33044216]


#### Create the following matrix:

In [17]:
arr=np.arange(0.01,1.01,0.01)
arr=arr.reshape(10,10)
print(arr)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [18]:
arr=np.arange(0,1.01,0.05263158)
arr[19]=1

print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.2631579
 0.31578948 0.36842106 0.42105264 0.47368422 0.5263158  0.57894738
 0.63157896 0.68421054 0.73684212 0.7894737  0.84210528 0.89473686
 0.94736844 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [19]:
arr=np.arange(1,26)
arr=arr.reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [20]:
arr1=np.arange(12,16)
arr2=np.arange(17,21)
arr3=np.arange(22,26)
arr=np.concatenate((arr1,arr2,arr3))
arr=arr.reshape(3,4)

print(arr)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [21]:
arr=np.array(20)
print(arr)

20


In [22]:
import numpy as np

arr=np.array([[ 2],[ 7],[12]])
print(arr)

[[ 2]
 [ 7]
 [12]]


In [23]:
arr=np.arange(21,26)
print(arr)

[21 22 23 24 25]


In [24]:
arr=np.arange(16,26)
arr=arr.reshape(2,5)
print(arr)

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!